### ISSUE TITLE
List<? extends MyType> fails since 0.4.6

### ISSUE THREAD

**Issue by reinra** [rharter/auto-value-gson#114]
If you add a following method it fails in the new version (passes with 0.4.5)
public abstract List<? extends MyType> bar();

```
../AutoValue_Foo.java:117: error: illegal start of expression
      this.fooAdapter = (TypeAdapter<List<? extends MyType>>) gson.getAdapter(TypeToken.getParameterized(List.class, ? extends MyType.class));
                                                                                                                                         ^
.../AutoValue_Foo.java:117: error: illegal start of expression
      this.fooAdapter = (TypeAdapter<List<? extends MyType>>) gson.getAdapter(TypeToken.getParameterized(List.class, ? extends MyType.class));
                                                                                                                                           ^
2 errors
```

**Comment by JakeWharton** [comment]
If you want, you can send a PR that ports https://github.com/rharter/auto-value-moshi/pull/78 to this library.

**Comment by hzsweers** [comment]
I'll open a PR

**Comment by ar-g** [comment]
I have similar issue 
``` 
java.lang.NoSuchMethodError: No static method getParameterized(Ljava/lang/reflect/Type;[Ljava/lang/reflect/Type;)Lcom/google/gson/reflect/TypeToken; in class Lcom/google/gson/reflect/TypeToken; or its super classes (declaration of 'com.google.gson.reflect.TypeToken' appears in /data/app/com.ex/base.apk:classes94.dex)
```

**Comment by reinra** [comment]
In my case I just replaced List<? extends MyType> with List<MyType> as I didn't actually have any sub classes. It was just weird that it used to work and started to fail. I don't know if it would actually even work with sub types as the actual type should be then written and read as well.

**Comment by ar-g** [comment]
@reinra do you think I should open another issue? My setup
```
@AutoValue public abstract class User {

  @SerializedName("social_profiles") public abstract List<SocialProfile> socialProfiles();

 public static TypeAdapter<SocialData> typeAdapter(Gson gson) {
    return new AutoValue_SocialData.GsonTypeAdapter(gson);
  }
}

@AutoValue public abstract class SocialProfile {
  @SerializedName("social_name") public abstract String socialName();
  @SerializedName("social_id") public abstract int socialId();
  @SerializedName("social_user_id") public abstract long socialUserId();

  public static TypeAdapter<SocialProfile> typeAdapter(Gson gson) {
    return new AutoValue_SocialProfile.GsonTypeAdapter(gson);
  }
}
```

**Comment by reinra** [comment]
I think in your case you should just upgrade the GSON library that's used at runtime. I also got the `NoSuchMethodError` after upgrading auto-value-gson but not upgrading the gson library itself yet.

**Comment by ar-g** [comment]
@reinra you were right, cheers!

**Comment by hzsweers** [comment]
I forgot about this. Will circle back to it this week

**Comment by hzsweers** [comment]
So there's three options here. Context is that auto-value-moshi handles this nicely because its `Types` class has helpers for subType and superType. Gson doesn't as far as I know.

1. Propose adding this as a helper to `TypeToken` and wait for a new Gson release with it
2. Add the utility to auto-value-gson-annotations, but that would make them required and not really an annotations artifact anymore
3. Generate (complex) anonymous inner instances. Would work everywhere but has duplicated code implications and generally rough

Thoughts?

**Comment by JakeWharton** [comment]
You should pretend that Gson is dead and will never see another release.

**Comment by hzsweers** [comment]
So I talked with @rharter and we're gonna go with an option 4:

* New optional `auto-value-gson-runtime` artifact that (for now) will just contain a copy of Moshi's `Types` utils, all `internal`-only APIs and nothing public.
* Since it's the same API, we'll also support just using Moshi's if it's available already
* If you don't use wildcard types, you can ignore this dependency. If we encounter one in processing and don't have either API option available though, we'll error out and ask that one is added.

Ideally, we can do this all auto-magically by looking at the classpath. Worst case, we can add an apt option to manually specify.

We can also consider deprecating the existing auto-value-gson-annotations artifact and folding it into the runtime if folks think consolidating is better (please chime in).

**Comment by hzsweers** [comment]
Actually yeah, let's deprecate the annotations artifact since it's already kind of an awkward setup anyway by containing more than just annotations
