### ISSUE TITLE
Request: Support property normalization and validation

### ISSUE THREAD

**Issue by bryanstern** [rharter/auto-value-gson#132]
Currently the generated `GsonTypeAdapter` uses the generated constructor when creating an instance of the class being deserialized. Unfortunately, this skips over any additional normalization or validation the class might doing in a factory method or builder.

It'd be great the generated `GsonTypeAdapter` accepted an optional custom factory. Something like:
```java
package com.ryanharter.auto.value.gson.example;

import com.google.auto.value.AutoValue;
import com.google.common.base.Preconditions;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;

@AutoValue public abstract class User {
  abstract String firstname();
  abstract String lastname();
  abstract int age();

  public static User create(String firstName, String lastName, int age) {
    Preconditions.checkArgument(!firstName.isEmpty());
    Preconditions.checkArgument(!lastName.isEmpty());
    if (age < 0) {
      age = 0;
    }

    return new AutoValue_User(firstName, lastName, age);
  }

  public static TypeAdapter<User> typeAdapter(Gson gson) {
    return new AutoValue_User.GsonTypeAdapter(gson, new AutoValue_User.GsonTypeAdapter.Factory() {
      @Override
      public User create(String firstname, String lastname, int age) {
        return User.create(firstname, lastname, age);
      }
    });
  }
}
```

Thoughts?

**Comment by hzsweers** [comment]
there's currently some default value support that we've planned to turn off by default in favor of pushing for access to autovalue builders in the extensions API, but this is an interesting alternative since it only makes it one added method rather than a bunch of mutating ones that the generated adapters currently have.

Do you have any other examples? Of the one you sent, my first inclination would actually be to just drop that model on the floor as invalid, or at least move the validation out.

**Comment by bryanstern** [comment]
I agree that example is kind of trivial. The main benefit of this is that it allows the same validation/normalization guarantees whether the object was created via a factory method, builder, or was deserialized from json.

My specific motivation is that I am receiving some json I need to deserialize and unfortunately the schema is not well respected by the sender resulting in writing custom deserializers to handle this.

One example that comes to mind is where two properties might be optional, but they should either both be present or absent. There isn't a great way to correct for this unless.

**Comment by rharter** [comment]
This would also be good to support without Builders, like in your example, and could probably already be done by simply annotating the main, all arg static factory method that you want the TypeAdapters to use.

I like the factory method that you propose, we could simply provide an optional second arg with a factory, and will generate a default one that calls the `AutoValue_Foo()` constructor.

**Comment by bejibx** [comment]
This is especially important for ensuring that all list/map/... members are immutable. With builders you can wrap those properties into unmodifiable wrappers during normalization. When deserializing from json you will actually get mutable objects because there is no way to normalize those properties.

**Comment by rharter** [comment]
This is an interesting solution. It seems easy enough to add a single
create method that, but default, will use the AV constructor to creat the
object, but can be optionally overridden by the user.

**Comment by bejibx** [comment]
This way you have to make all normalization methods static so you can use them both in builder and overriden constructor. Could be messy if there is lot of them.

**Comment by rharter** [comment]
I don't think it would really add anything except one extra method from the current implementation.  By simply adding one layer of indirection, a `create` method, on the TypeAdapter, the user could use this, or not and not notice any difference.

```
class AutoValue_Foo {

  public class GsonTypeAdapter extends TypeAdapter {
    ...

    public Foo create(String name, String bar) {
      return new AutoValue_Foo(name, bar);
    }
  }

}
```

With something like that, instead of the type adapter calling the constructor directly, it calls the constructor via the `create` method, and that allows the user to override it however they want.  They could not override it and it works like normal, they could perform validation or normalization and then call the constructor, or they could call the builder.

This is also would provide a great way to support the builder type work @bryanstern is waiting on the AV guys for.  Once we get builder support in the extension API, we can fill that method body with constructor/builder/annotated static factory method by default.

**Comment by bryanstern** [comment]
Added in #224
