### ISSUE TITLE
Add support for the @Since and @Until annotations.

### ISSUE THREAD

**Issue by wberlinic** [rharter/auto-value-gson#153]
[Since](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/annotations/Since.java)
[Until](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/annotations/Until.java)

These annotations allow mapping the json class members to specific web service api versions.  They are not available for methods, however.  auto-value-gson could define equivalent method level annotations and put those in the generated class on its members.

Ex.
```
@AutoValue
public abstract class AutoValueClass{
    @Since(1.0)
    abstract int namedMember();
}
```

**Comment by JakeWharton** [comment]
The generated code is not passed through Gson's reflective type adapter
which honors these annotations. The generated code is the type adapter and
would have to bake in support for these itself.

**Comment by wberlinic** [comment]
I see. What does auto-value-gson do if the json is missing a field? Presumably the same as [gson](https://github.com/google/gson/blob/master/UserGuide.md#finer-points-with-objects)?
> While deserializing, a missing entry in JSON results in setting the corresponding field in the object to null

Similarly for null fields?
>While serializing, a null field is skipped from the output

If so, I can achieve the same thing by manually setting nulls/checking for nulls with newer service api's.

**Comment by wberlinic** [comment]
It looks to me like AutoValue will generate null checks for any parameters that are not marked with @Nullable so one would likely need to include that annotation as well.

**Comment by rharter** [comment]
To be "complete" an AutoValue object either has to have all non-nullable
(or non-optional) fields set.  This means that if a required object field
in your value object doesn't exist in the JSON, it will fail. Primitives
will get default values.  To mitigate this, you can set all properties that
don't exist in all api versions to `Optional`, that way your consumers know
that they might not be there and will have to check.

Even if `@Since` and `@Until` were supported, you would have to either wrap
the properties  `Optional` or mark them as `@Nullable`, since they won't
always be present.  At that point `@Since` and `@Until` basically become
documentation.

**Comment by wberlinic** [comment]
I agree with the assessment. Due to the limitations of using AutoValue (non-required fields must be Optional/marked Nullable) there is no reason to implement `@Since` and `@Until`.
