### ISSUE TITLE
What should the default collection policy be?

### ISSUE THREAD

**Issue by rharter** [rharter/auto-value-gson#73]
Recently the functionality of collections was changed to default to empty collections, instead of null (#71), but this technically breaks the contract with AutoValue, since the property is not annotation with `@Nullable`.  That means that it should technically exist in the JSON.  This potentially masks JSON encoding issues.

IMHO, the issue here is that deserializing and serializing are now no longer compatible, i.e. if you deserialize JSON that has a null collection property then serialize it using this extension, you won't be able to reproduce the original JSON, potentially with different meaning.

Recognizing the usefulness of this functionality, @hzsweers has proposed making this a non-default option configurable using apt arguments.  This ticket is to discuss the implications and determine what the default collection policy should be.

**Comment by hzsweers** [comment]
Yeah I think the default behavior should be strict (not present == `null`). In our case, we actually expect this behavior as part of validation, so we can throw out invalid models and track metrics around invalid responses. It also more accurately reflects the shape of the object passed, rather than making it a tribal knowledge-y "oh yeah we just *do* that". 

I can see the value of coercing to empty lists to avoid the nullcheck and dealing with finicky APIs, but I think that should be an opt-in rather than an opt-out.

**Comment by hzsweers** [comment]
Any update on this?

**Comment by rharter** [comment]
I agree with you that coercing null collections to empty collections should be opt in, and am in favor of your proposal of the apt argument config.

**Comment by hzsweers** [comment]
Alrighty, I can send a pr soon :)
