### ISSUE TITLE
Ship a default "MyAdapterFactory" with `auto-value-gson`.

### ISSUE THREAD

**Issue by jaredsburrows** [rharter/auto-value-gson#76]
Can a default, "basic", `TypeAdapterFactory` be shipped with `auto-value-gson`? Such as the one from https://github.com/rharter/auto-value-gson#factory.

**Code:**

```
@GsonTypeAdapterFactory
public abstract class MyAdapterFactory implements TypeAdapterFactory {

  // Static factory method to access the package
  // private generated implementation
  public static TypeAdapterFactory create() {
    return new AutoValueGson_MyAdapterFactory();
  }

}
```

**Generated Code:**

```
public final class AutoValueGson_MyAdapterFactory extends MyAdapterFactory {
  @Override
  @SuppressWarnings("unchecked")
  public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
    Class<T> rawType = (Class<T>) type.getRawType();
    if (Media.class.isAssignableFrom(rawType)) {
      return (TypeAdapter<T>) Media.typeAdapter(gson);
    } else {
      return null;
    }
  }
}
```

We can add a new module with this class to add to the `compile` configuration.

**Comment by rharter** [comment]
I wouldn't package one in it, since it's optional, but you could always
make a lib that's really just that and include it as a second dependency.

On Sat, Oct 22, 2016, 5:27 AM Jared Burrows <notifications@github.com>
wrote:

Can a default, "basic", TypeAdapterFactory be shipped with auto-value-gson?
Such as the one from https://github.com/rharter/auto-value-gson#factory.

@GsonTypeAdapterFactory
public abstract class MyAdapterFactory implements TypeAdapterFactory {

  // Static factory method to access the package
  // private generated implementation
  public static TypeAdapterFactory create() {
    return new AutoValueGson_MyAdapterFactory();
  }

}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rharter/auto-value-gson/issues/76>, or mute the thread
