### ISSUE TITLE
@SerizalizedName not working with Builder

### ISSUE THREAD

**Issue by lukasz-gosiewski** [rharter/auto-value-gson#95]
This annotation does not work when we are annotating properties in class that uses Builder to create it's instances. In generated code just getters are annotated, setters not.

**Comment by hzsweers** [comment]
Builders are not currently exposed in the autovalue extensions API, auto-value-gson can't inspect them or modify them.

**Comment by hzsweers** [comment]
I would argue this is outside of the scope of this library too, as builders don't go through autovaluegson anyway

**Comment by rharter** [comment]
As in you're putting `@SerializedName` on a Builder's getters or setters?  That's not supposed to work.

This extension doesn't have anything to do with Builders, it merely creates type adapters from your `@AutoValue` annotated classes.

**Comment by rharter** [comment]
@lukasz-gosiewski is this still an issue?  If not I'll close it.

**Comment by lukasz-gosiewski** [comment]
@rharter All the time, but I may understand usability of this lib wrong. If noone except me feels that it's wrong it can be issue with me, not the lib :)

**Comment by lukasz-gosiewski** [comment]
I will just leave a note for you to better understand what was I trying to achive:
Imagine you have and app where you want to use Auto-value. I are using GSON too. But the fields of your classes are not exactly the same name that JSON fields are. Moreover you have need to use builder (in fact it's irrevelant why, but let's assume that you have some non-critical fields in big class, and don't want to overload so much constructors). If I annotate fields of AutoValue class with @SerializedName this annoation is copied to normal class fields, but have no use in builder for GSON. So now - when GSON is trying to build an object, and fields are public - it works fine, GSON is using @SerializedName names, but when fields are private, and builder is in use - GSON is ignoring @SerizalizedName and trying to find the exact same names on fields to mach JSON. That's all.

**Comment by hzsweers** [comment]
>  But the fields of your classes are not exactly the same name that JSON fields are

I'm not sure I follow this bit. a-v-g doesn't generate the backing fields for the autovalue implementation, its extension just creates the gson adapter layer.

**Comment by rharter** [comment]
I think there are a couple of things at play here.

> I annotate fields of AutoValue class with @SerializedName this annoation is copied to normal class fields, but have no use in builder for GSON.

That's an artifact of AutoValue, but not really how a-v-g works. While yes, the annotations may be copied to backing fields, the value of a-v-g is that it generates a type adapter for you, so it doesn't end up using GSON's built in annotation reading mechanism during deserialization. At compile time a-v-g reads those annotations and uses the values in the custom generated TypeAdapter to deserialization JSON.

> So now - when GSON is trying to build an object, and fields are public - it works fine, GSON is using @SerializedName names, but when fields are private, and builder is in use - GSON is ignoring @SerizalizedName and trying to find the exact same names on fields to mach JSON.

That's also not entirely true. A-v-g creates a TypeAdapter that will use your `@SerializedName` attributes from your annotated class and construct an object using the constructor, whether you have a builder or not (it's generated code, so who cares if it's long). It doesn't matter that the backing fields are private, because Gson never sees them. 

Without a code sample, it sounds to me like you're trying to use GSON's built in reflection based deserializer to deserialize AV classes, and thinking that since the fields with the annotations are private you need to deserialize directly to a builder, but that's not how a-v-g works. It creates an internal TypeAdapter that manually deserialize an object from JSON. To use it, you have to add it to your Gson instance, then deserialize an object and it'll use the constructor to creat your AV object, whether you use Builders to manually create them or not. It will also use your `@SerializedName` attributes that you put on the abstract methods of your AV class.
